# Generated by Django 4.1.7 on 2023-05-13 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(default='', max_length=50, verbose_name='uniqueId')),
                ('DocUniqueId', models.CharField(default='', max_length=50, verbose_name='DocUniqueId')),
                ('appointmentTime', models.CharField(max_length=30, verbose_name='appointmentTime')),
                ('appointmentDate', models.CharField(max_length=30, verbose_name='appointmentDate')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'DocAppointments',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docUniqueId', models.CharField(default='', max_length=50)),
                ('doctorName', models.CharField(default='', max_length=50)),
                ('clinicName', models.CharField(default='', max_length=50)),
                ('contactNo', models.CharField(default='', max_length=50)),
                ('speciality', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=250)),
                ('appointmentstartTime', models.CharField(default='', max_length=250)),
                ('appointmentendTime', models.CharField(default='', max_length=250)),
                ('availableDays', models.CharField(default='', max_length=50)),
                ('appointmentFees', models.IntegerField(default=0, verbose_name='fee')),
                ('upiId', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=30)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('authToken', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Doctor',
            },
        ),
    ]
