# Generated by Django 3.2.6 on 2023-05-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_doctor_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='authToken',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
