# Generated by Django 3.2.6 on 2023-05-10 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_doctor_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(default='', max_length=50)),
                ('appointmentTime', models.TimeField()),
                ('appointmentDate', models.DateField()),
                ('DocUniqueId', models.CharField(default='', max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'DocAppointments',
            },
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='uniqueId',
            new_name='docUniqueId',
        ),
    ]
