# Generated by Django 3.2.6 on 2023-05-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20230510_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docappointments',
            name='appointmentDate',
            field=models.DateField(verbose_name='appointmentDate'),
        ),
        migrations.AlterField(
            model_name='docappointments',
            name='appointmentTime',
            field=models.TimeField(verbose_name='appointmentTime'),
        ),
    ]
