# Generated by Django 3.2.6 on 2023-05-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_auto_20230510_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docappointments',
            name='DocUniqueId',
            field=models.CharField(default='', max_length=50, verbose_name='DocUniqueId'),
        ),
        migrations.AlterField(
            model_name='docappointments',
            name='uniqueId',
            field=models.CharField(default='', max_length=50, verbose_name='uniqueId'),
        ),
    ]
