# Generated by Django 3.2.6 on 2023-05-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_auto_20230510_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='confirmPassword',
        ),
    ]
