# Generated by Django 3.2.6 on 2023-05-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_remove_doctor_confirmpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availableDays',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinicName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctorName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='upiId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
