# Generated by Django 4.1.7 on 2023-05-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0009_auto_20230512_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='appointmentendTime',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='appointmentstartTime',
            field=models.CharField(default='', max_length=250),
        ),
    ]
