# Generated by Django 4.2.1 on 2023-05-11 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uniqueId", models.CharField(default="", max_length=50)),
                ("order", models.CharField(max_length=50)),
                ("orderTime", models.CharField(max_length=100)),
                ("status", models.CharField(default="", max_length=50)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Order",
            },
        ),
    ]
