# Generated by Django 4.1.7 on 2023-05-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='closingTime',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='openingTime',
            field=models.CharField(default='', max_length=10),
        ),
    ]
