# Generated by Django 3.2.6 on 2023-05-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_clinic_closingtime_alter_clinic_openingtime'),
        ('clinic', '0002_clinic_contactno'),
    ]

    operations = [
    ]
