# Generated by Django 4.2a1 on 2023-05-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_clinic_closingtime_alter_clinic_openingtime'),
        ('clinic', '0002_clinic_contactno'),
    ]

    operations = [
    ]
