# Generated by Django 3.2.6 on 2023-05-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_clinic_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='contactNo',
            field=models.CharField(default='', max_length=15),
        ),
    ]
