# Generated by Django 3.2.6 on 2023-05-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_clinic_contactno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='confirmPassword',
        ),
    ]
