# Generated by Django 3.2.6 on 2023-05-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20230512_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='closingTime',
        ),
    ]
