# Generated by Django 4.2a1 on 2023-04-14 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(default='', max_length=50)),
                ('patientName', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('contactNo', models.CharField(default='', max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('confirmPassword', models.CharField(max_length=30)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
